"""Tests that pin agreement across reusables is not just a comment.

Three reusables in `.github/workflows/` declare a Rust `toolchain` input,
two env values for shellcheck/actionlint ride on three workflows, and a
shellcheck input default travels on two. Each value is pinned on its own,
but no comment in any of the files compared them until rust-supply-chain
drifted to 1.97 while rust-ci and rust-audit were already on 1.98. A
release's SBOM and license attribution were then produced by a compiler
the test suite never ran — the defect Glyndor/podup#1487 recorded.

A comment about "keep these equal" does not fail when one of them stops
being equal. These tests parse the workflow YAML directly (no subprocess,
no network, no `gh`) and fail the run when the pins diverge, so a future
drift trips CI on the bump PR instead of three months later on a release
artifact.

The four invariants:

1. The Rust `toolchain` defaults in `rust-ci.yml`, `rust-audit.yml`, and
   `rust-supply-chain.yml` all agree.
2. The shared Rust toolchain value is a two-component version (`1.98`,
   not `1.98.0` and not `stable`) — `rustup toolchain install` accepts
   all three and they mean different things, so the shape is part of the
   contract.
3. The `SHELLCHECK_VERSION` env value in `actionlint.yml` matches the
   `shellcheck-version` input defaults in `workflow-lint.yml` and
   `shell-ci.yml`. The shape that drifts is "two of three bumped" —
   one workflow's author updates one pin, the others stay.
4. The `ACTIONLINT_VERSION` env value in `actionlint.yml` matches the
   one in `workflow-lint.yml`.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
WORKFLOWS_DIR = REPO_ROOT / ".github" / "workflows"


def _default_for(workflow: str, input_name: str) -> str:
    """Return the declared default of `input_name` in `workflow`.

    Reads the workflow file with `yaml.safe_load`, walks down to
    `on.workflow_call.inputs.<input_name>.default`, and returns the
    string. Fails the test with a clear, named message if any link in
    that chain is missing — never returns None silently, because a silent
    None would let a missing default pass an equality check.

    YAML 1.1 reads the bare `on:` key in a GitHub Actions workflow as the
    Python boolean `True`. PyYAML 6.x keeps that behaviour here, so the
    parsed key is `True`; older or YAML-1.2-only resolvers can surface
    it as the string `"on"` instead. Both are handled.
    """
    path = WORKFLOWS_DIR / workflow
    if not path.is_file():
        pytest.fail(f"{workflow}: file not found at {path}")
    try:
        with path.open() as fh:
            doc = yaml.safe_load(fh)
    except yaml.YAMLError as e:
        pytest.fail(f"{workflow}: YAML parse error: {e}")
    if not isinstance(doc, dict):
        pytest.fail(f"{workflow}: top-level YAML is not a mapping")
    # Both keys are possible across YAML resolvers; try both.
    on_node = doc.get(True) if True in doc else doc.get("on")
    if on_node is None:
        pytest.fail(f"{workflow}: missing `on:` section")
    if not isinstance(on_node, dict):
        pytest.fail(
            f"{workflow}: `on:` is not a mapping (got {type(on_node).__name__})"
        )
    workflow_call = on_node.get("workflow_call")
    if not isinstance(workflow_call, dict):
        pytest.fail(f"{workflow}: missing `on.workflow_call` section")
    inputs = workflow_call.get("inputs")
    if not isinstance(inputs, dict):
        pytest.fail(f"{workflow}: missing `on.workflow_call.inputs` section")
    input_spec = inputs.get(input_name)
    if not isinstance(input_spec, dict):
        pytest.fail(f"{workflow}: missing input `{input_name}`")
    if "default" not in input_spec:
        pytest.fail(f"{workflow}: input `{input_name}` has no `default`")
    default = input_spec["default"]
    if not isinstance(default, str):
        pytest.fail(
            f"{workflow}: input `{input_name}` default is {type(default).__name__}, "
            f"expected string"
        )
    return default


# --- 1. The three Rust toolchain pins agree ------------------------------


def test_every_rust_toolchain_default_agrees() -> None:
    """The three Rust reusables ship the same pinned toolchain.

    Real event: rust-supply-chain.yml sat on Rust 1.97 for an extended
    period while rust-ci.yml and rust-audit.yml had already moved to
    1.98, because a toolchain bump raised two and not the third and
    nothing compared them. The release's SBOM and license attribution
    were then generated by a compiler the test suite never ran — the
    defect Glyndor/podup#1487 recorded. A test asserting agreement is
    the only shape that catches that class of drift on the bump PR
    rather than at release time.

    Assertion message lists every file with its value so the failure
    says which one moved, not just that they differ. The expected
    version is intentionally NOT hardcoded — the test is about
    agreement, not about a number, so it survives the next bump and
    only fails on divergence.
    """
    files = ("rust-ci.yml", "rust-audit.yml", "rust-supply-chain.yml")
    values = {wf: _default_for(wf, "toolchain") for wf in files}
    distinct = set(values.values())
    if len(distinct) != 1:
        breakdown = ", ".join(f"{wf}={v!r}" for wf, v in values.items())
        pytest.fail(
            f"Rust toolchain defaults disagree: {breakdown}. "
            f"All three reusables must pin the same toolchain — see "
            f"rust-supply-chain.yml's toolchain comment and the regression "
            f"recorded in Glyndor/podup#1487."
        )


def test_rust_toolchain_is_a_two_component_version() -> None:
    """The shared Rust toolchain value matches `MAJOR.MINOR`.

    `rustup toolchain install` accepts three shapes that mean different
    things: a floating channel like `stable` (always the latest stable
    release — which is why every other input here pins an exact version),
    a fully-qualified triple like `1.98.0` (a single patch release, not a
    channel), and the two-component channel like `1.98` (the stable
    release on that minor — what the three reusables use). The shape is
    part of the contract: a bump from `1.98` to `1.98.0` silently changes
    caching and reproducibility without surfacing a difference in any
    input name, and a reversion to `stable` undoes the whole pinning
    story.

    Every file is checked — not just one — because the failure mode is
    a single-file drift while the other two still say `1.98`: reading
    only the first value would let that drift pass.

    Real event: no single drift has happened here, but the equivalent
    drift would be a future PR that flips one of the three from `1.98`
    to `stable` and slips through review because the test the audit
    called out didn't exist.
    """
    files = ("rust-ci.yml", "rust-audit.yml", "rust-supply-chain.yml")
    values = {wf: _default_for(wf, "toolchain") for wf in files}
    bad = {wf: v for wf, v in values.items() if not re.fullmatch(r"[0-9]+\.[0-9]+", v)}
    if bad:
        breakdown = ", ".join(f"{wf}={v!r}" for wf, v in sorted(bad.items()))
        pytest.fail(
            f"Rust toolchain default is not a two-component version: "
            f"{breakdown}. Expected MAJOR.MINOR like '1.98'. `stable` "
            f"floats; '1.98.0' pins a single patch; only MAJOR.MINOR pins "
            f"the stable release on that minor."
        )


# --- 2. Shellcheck version agrees across the three workflows ----------


# Matches a literal env value (skips `${{ ... }}` expressions, which are
# references, not values). Captures the first non-whitespace, non-comment
# token after the colon.
_SHELLCHECK_ENV_VALUE = re.compile(
    r"^\s*SHELLCHECK_VERSION:\s*([^\s\"'#][^\s\"']*|[^\s\"'{][^\s\"']*)\s*$",
    re.MULTILINE,
)
# Matches an input `shellcheck-version:` block and the `default:` line
# inside it. The capture is the default value, without surrounding quotes
# or trailing whitespace. `re.MULTILINE` makes `^` and `$` line-aware.
_SHELLCHECK_INPUT_DEFAULT = re.compile(
    r"^\s*shellcheck-version:\s*$\n"
    r"(?:[^\n]*\n)*?"
    r"^\s*default:\s*[\"']?([^\s\"'#]+)[\"']?\s*$",
    re.MULTILINE,
)


def _shellcheck_values() -> dict[str, str]:
    """Return `{source: value}` for every SHELLCHECK_VERSION literal and
    shellcheck-version default across the workflows directory.

    Two patterns cover the two shapes the workflows use: a literal
    `SHELLCHECK_VERSION: vX.Y.Z` env entry (actionlint.yml), and a
    `shellcheck-version: ... default: "vX.Y.Z"` input block
    (workflow-lint.yml, shell-ci.yml). Both are returned with a
    `source` key naming the file so a divergence message points at
    the actual occurrence.
    """
    found: dict[str, str] = {}
    for path in sorted(WORKFLOWS_DIR.glob("*.yml")):
        text = path.read_text()
        for m in _SHELLCHECK_ENV_VALUE.finditer(text):
            key = f"{path.name}:SHELLCHECK_VERSION(env)"
            found[key] = m.group(1)
        for m in _SHELLCHECK_INPUT_DEFAULT.finditer(text):
            key = f"{path.name}:shellcheck-version(input.default)"
            found[key] = m.group(1)
    return found


def test_shellcheck_version_agrees_across_workflows() -> None:
    """Every SHELLCHECK_VERSION env value and shellcheck-version input
    default across the workflows directory agrees.

    The same drift shape as the Rust toolchain: one workflow author
    bumps one pin, the others stay. There is no comment that compares
    these three and the same defect (two of three bumped) would land
    here if any one of them drifted.

    Real event: no shellcheck version drift has been recorded, but the
    failure mode this defends against is the same one
    `test_every_rust_toolchain_default_agrees` was written for — an
    audit missed one bump and three workflows no longer lint each other
    to a compatible version. The test exists so the next bump is
    blocked at the PR.
    """
    found = _shellcheck_values()
    if len(found) < 2:
        pytest.fail(
            f"Found only {len(found)} SHELLCHECK_VERSION/shellcheck-version "
            f"occurrences: {found}. Expected at least two."
        )
    distinct = set(found.values())
    if len(distinct) != 1:
        breakdown = ", ".join(f"{k}={v!r}" for k, v in sorted(found.items()))
        pytest.fail(
            f"Shellcheck version disagrees across workflows: {breakdown}. "
            f"All workflows must install the same shellcheck release so "
            f"a workflow this repo lints for itself is also the one it "
            f"ships to consumers."
        )


# --- 3. Actionlint version agrees across the two workflows ----------


_ACTIONLINT_ENV_VALUE = re.compile(
    r"^\s*ACTIONLINT_VERSION:\s*([^\s\"'#][^\s\"']*|[^\s\"'{][^\s\"']*)\s*$",
    re.MULTILINE,
)


def _actionlint_values() -> dict[str, str]:
    """Return `{source: value}` for every ACTIONLINT_VERSION literal
    across the workflows directory.

    Actionlint is only declared as a literal env value in two files
    (actionlint.yml, workflow-lint.yml), so there is no input-default
    variant to scan for.
    """
    found: dict[str, str] = {}
    for path in sorted(WORKFLOWS_DIR.glob("*.yml")):
        text = path.read_text()
        for m in _ACTIONLINT_ENV_VALUE.finditer(text):
            key = f"{path.name}:ACTIONLINT_VERSION(env)"
            found[key] = m.group(1)
    return found


def test_actionlint_version_agrees_across_workflows() -> None:
    """Every ACTIONLINT_VERSION env value across the workflows directory
    agrees.

    Same shape as the shellcheck test, applied to actionlint. The two
    workflows both pin the same release so actionlint reports the same
    lints when the repo lints itself as it does when it lints a
    consumer's checkout.

    Real event: no actionlint version drift has been recorded, but the
    failure mode being defended against is the two-of-three class
    described in `test_every_rust_toolchain_default_agrees` — one
    workflow's author bumps one pin, the other stays, and the two
    linters start disagreeing about what the same workflow means.
    """
    found = _actionlint_values()
    if len(found) < 2:
        pytest.fail(
            f"Found only {len(found)} ACTIONLINT_VERSION occurrences: {found}. "
            f"Expected at least two."
        )
    distinct = set(found.values())
    if len(distinct) != 1:
        breakdown = ", ".join(f"{k}={v!r}" for k, v in sorted(found.items()))
        pytest.fail(
            f"Actionlint version disagrees across workflows: {breakdown}. "
            f"actionlint.yml and workflow-lint.yml must pin the same release."
        )
